version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: card-billing-db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: card_billing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: card-billing-db-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432
    command: sh -c "npx prisma db push && yarn start:prod"

volumes:
  postgres_data:
